#!/bin/bash
echo "Le nom de scripte est : "$0
echo "Le premier argument est :  "$1
echo "Le second argument est :  "$2
echo "Tous les arguments :  "$*
echo "Nombre total d'arguments :  "$#
echo "Le premier argument contien :"${#1}   "caracteres"
echo "Le premier argument contien :"${#2}  "caracteres"

#commit 2
#commit 3
